version: '3.8'
services:
  app:
    build: .
    ports:
      - "8181:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/timetrack
      SPRING_DATASOURCE_USERNAME: krainet
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: timetrack
      POSTGRES_USER: krainet
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./struct/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin



volumes:
  db-data:
  postgres_data:
  pgadmin-data:
