CREATE TABLE role
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       VARCHAR(255)                            NOT NULL,
    user_role_id  BIGINT,
    user_name     VARCHAR(255)                            NOT NULL,
    user_login    VARCHAR(255)                            NOT NULL,
    user_password VARCHAR(255)                            NOT NULL,
    user_email    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_USER_ROLE FOREIGN KEY (user_role_id) REFERENCES role (id);