CREATE TABLE employee
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id       VARCHAR(255)                            NOT NULL,
    employee_role_id  BIGINT,
    employee_login    VARCHAR(255)                            NOT NULL,
    employee_password VARCHAR(255)                            NOT NULL,
    employee_email    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (id)
);

CREATE TABLE employee_tasks
(
    employee_id BIGINT NOT NULL,
    tasks_id    BIGINT NOT NULL
);

CREATE TABLE project
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id         VARCHAR(255)                            NOT NULL,
    project_name       VARCHAR(255)                            NOT NULL,
    project_start_date date                                    NOT NULL,
    project_end_date   date                                    NOT NULL,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE record
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    record_time time WITHOUT TIME ZONE                  NOT NULL,
    employee_id BIGINT,
    task_id     BIGINT,
    CONSTRAINT pk_record PRIMARY KEY (id)
);

CREATE TABLE role
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE task
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    task_id                  VARCHAR(255)                            NOT NULL,
    task_name                VARCHAR(255)                            NOT NULL,
    task_required_start_date date                                    NOT NULL,
    task_required_end_date   date                                    NOT NULL,
    project_id               BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE employee_tasks
    ADD CONSTRAINT uc_employee_tasks_tasks UNIQUE (tasks_id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_EMPLOYEE_ROLE FOREIGN KEY (employee_role_id) REFERENCES role (id);

ALTER TABLE record
    ADD CONSTRAINT FK_RECORD_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE record
    ADD CONSTRAINT FK_RECORD_ON_TASK FOREIGN KEY (task_id) REFERENCES task (id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE employee_tasks
    ADD CONSTRAINT fk_emptas_on_employee FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE employee_tasks
    ADD CONSTRAINT fk_emptas_on_task FOREIGN KEY (tasks_id) REFERENCES task (id);